# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

notifications:
  email: false
language: objective-c
osx_image: xcode8
before_install:
  - cd Examples/
  - pod install
script:
  - set -o pipefail
  - xcodebuild $XCODE_ACTION
      -workspace "WBNetworkingLite.xcworkspace"
      -scheme "WBNetworkingLite-Example"
      -sdk "$XCODE_SDK"
      -destination "$XCODE_DESTINATION"
      | xcpretty
